### ISSUE TITLE
Unable to server the model locally using mlflow

### ISSUE THREAD

**Issue by Kaushik-Rao** [Maherstad/DETR-ObjectDetect-WebApp-MLFlow#1]
First of all, thank you for this amazing project, I've got many insights on MLOps and MLflow

I'm stuck at 4th step,

mlflow models serve -m <path_to_model> -p 7000 --no-conda

which path are you referring to in this command, cuz i used the path which is available in the MLFlow dashboard of my model, but the page says as 

![image](https://github.com/Maherstad/DETR-ObjectDetect-WebApp-MLFlow/assets/82809753/005c140b-7991-4d9a-b6c6-6a96a2caae5c)

I searched there are other options for this code such as, model:/<name-of-the-model/version  , but it says no such model exist

Can you kindly help me with this

**Comment by Maherstad** [comment]
Hi Kaushik-Rao, 

thank you for your question , the path can be found in the mlflow UI as shown in the screenshot. 

![Screenshot (8)](https://github.com/Maherstad/DETR-ObjectDetect-WebApp-MLFlow/assets/30124102/e57f0c13-4adc-4349-b56a-47cb262e3eb7)

**Comment by Kaushik-Rao** [comment]
Thank you for the response, i remember i did use that path in the command but unfortunately i got that the same error as shown above. I was taking insights and trying to recreate this project for my Final B.Tech project, but due to this error i changed my deployment tech stack to streamlit.

**Comment by Maherstad** [comment]
Streamlit is also a great alternative if you want to put a face on your ML model for prototyping or presentation settings. Well done and good luck with your future projects!
